name: Helm

on:
  push:
    tags: ["helm*"]

jobs:
  Helm:
    name: lancement Helm
    runs-on: ubuntu-latest
    steps:
      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name 
      - name: Connexion à Openshift
        run: oc login --token=sha256~PjEzP_iqaBRuaKXLtKGUJBTLN0GpnzV5mEUparnJ_nM --server=https://api.openshift.kakor.ovh:6443
      - name: Deployment Helm
        run: helm upgrade --install groupe-4 librairie-helm/ --set image=<urlimage>:${{ github.ref_name }}
